### ISSUE TITLE
Fix the problem with `coin collect --help`

### ISSUE THREAD

**Issue by snth** [snth/numismatic#3]
The following fails:

```
$ coin collect --help
Traceback (most recent call last):
  File "/opt/venv-numismatic/bin/coin", line 11, in <module>
    load_entry_point('numismatic', 'console_scripts', 'coin')()
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 1085, in invoke
    allow_interspersed_args=False)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 496, in get_help
    return self.command.get_help(self)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 830, in get_help
    self.format_help(ctx, formatter)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 845, in format_help
    self.format_options(ctx, formatter)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 859, in format_options
    rv = param.get_help_record(ctx)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 1608, in get_help_record
    rv = [_write_opts(self.opts)]
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 1605, in _write_opts
    rv += ' ' + self.make_metavar()
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/core.py", line 1298, in make_metavar
    metavar = self.type.get_metavar(self)
  File "/opt/venv-numismatic/lib/python3.6/site-packages/click/types.py", line 140, in get_metavar
    return '[%s]' % '|'.join(self.choices)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by snth** [comment]
Fixed by #4.
