### ISSUE TITLE
Error Installing on Mac Terminal

### ISSUE THREAD

**Issue by smrucv** [snth/numismatic#65]
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-14pvn2be/toolz/

I have no idea what could it be

**Comment by snth** [comment]
I'm sorry about your troubles. Have you tried `pip install toolz` and then tried again?

I haven't really worked on `numismatic` in quite a while. A project that I saw recently which seems to try to accomplish the same thing which you may want to try is: https://github.com/bmoscon/cryptofeed/
Please note that I have not used `cryptofeed` and am not associated with it in any way.

**Comment by Coder-Book** [comment]
It isn't just Mac. It is throwing an error on install (This is on Manjaro)

```txt
[coderbook@computer Downloads]$ sudo pip install numismatic
Collecting numismatic
  Downloading https://files.pythonhosted.org/packages/25/18/f18a83ae37e5ba8f697ec5fcde1d68da5be0fd8c80116fb5802b8d827bc0/numismatic-0.1.7-py3-none-any.whl
Collecting six==1.11.0 (from numismatic)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting certifi==2017.7.27.1 (from numismatic)
  Using cached https://files.pythonhosted.org/packages/40/66/06130724e8205fc8c105db7edb92871c7fff7d31324d7f4405c762624a43/certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting toolz==0.8.2 (from numismatic)
  Using cached https://files.pythonhosted.org/packages/75/9c/a26de5efd56009e15af607bff6d2a395631e3c20e7c64b861c9bc4b34288/toolz-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3c3dgii_/toolz/setup.py", line 5, in <module>
        import toolz
      File "/tmp/pip-install-3c3dgii_/toolz/toolz/__init__.py", line 3, in <module>
        from .functoolz import *
      File "/tmp/pip-install-3c3dgii_/toolz/toolz/functoolz.py", line 501
        f.__name__ for f in reversed((self.first,) + self.funcs),
        ^
    SyntaxError: Generator expression must be parenthesized
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3c3dgii_/toolz/
```
